name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:17

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: demo_db

        ports:
          - 5432:5432

        options: >-
          --health-cmd "pg_isready -U postgres -d demo_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        env:
          DB_URL: jdbc:postgresql://localhost:5432/demo_db
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: ./mvnw clean package